### ISSUE TITLE
PortAudio installation

### ISSUE THREAD

**Issue by florian-vuillemot** [florian-vuillemot/EpitechBabel#3]
Process for install PortAudio from source.

**Comment by ZelZorgia** [comment]
Install ubuntu 16.4 (ça marche que sur cette distrib (pas test arch))

http://www.portaudio.com/archives/pa_stable_v190600_20161030.tgz
sudo apt-get install libasound-dev

dans le dossier:
./configure && make
cp lib/.libs/libportaudio.a /YOUR/PROJECT/DIR

flags de compil:
libportaudio.a -lrt -lm -lasound -ljack -pthread
