### ISSUE TITLE
Opus installation

### ISSUE THREAD

**Issue by florian-vuillemot** [florian-vuillemot/EpitechBabel#4]
Process for install Opus from source.

**Comment by ZelZorgia** [comment]
Linux :
https://archive.mozilla.org/pub/opus/opus-tools-0.1.10.tar.gz
Windows:
https://archive.mozilla.org/pub/opus/win64/opus-tools-0.1.10-win64.zip

après y à des dépendances mais ça change en fonction de la distrib
./configure && make
